#pragma config(Sensor, S1,     IR,             sensorEV3_IRSensor)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(1)

	{
		displaySensorValues(1, IR);


	}



}
