#pragma config(Sensor, S1,     toque,          sensorTouch)
#pragma config(Motor,  motorA,          m,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1){
		if(SensorValue[toque]==1)
		{
			SensorValue[]
			setMotor(m, 80);
			wait(150, milliseconds);
			setMotor(m, -80);
			wait(177, milliseconds);
			stopAllMotors();
		}
	}


	//	while(1){
	//displayVariableValues(1,SensorValue[us]);
	//wait(200,milliseconds);
	//if(SensorValue[us]<25)
	//{
	//	displayText(1,"perto!!!!");
	//
	//}
	//else
	//{
	//	displayText(1,"Longe!!!!");
	//}
}
